version: "3.7"
services:
  frontend:
    build: frontend/
    ports:
      - "3000:80"
    environment:
      - SERVER_CORS_ALLOW_ORIGINS=http://localhost:8080,http://localhost:3000,http://localhost:8000

  backend:
    build: backend/
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DOMAIN=localhost:8000
      - BASE_URL=http://localhost:8000
      - OPENID_CLIENT_ID=e2esamplefrontend
      - FRONTEND_ORIGIN=http://localhost:3000
      - OPENID_ISSUER=http://localhost:8080/realms/master
      - OPENID_ISSUER_FETCH_KEYS=http://keycloak:8080/realms/master
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_PASSWORD=db-password
      - MONGODB_USERNAME=admin
    networks:
      - db
      - iam
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=db-password
    ports:
      - "27017:27017"
    networks:
      - db
      - iam

  # IAM - set up in mocked mode for now
  # You need to set up your own
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
    networks:
      - iam

networks:
  db:
    external: false
  iam:
    external: false
